# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-eks-github-actions-runner
  description: This component deploys self-hosted GitHub Actions Runners and a [Controller](https://docs
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
